import Head from 'next/head'
import { Maze } from '@/features/Maze';

export default function Home() {
  return (
    <>
      <Head>
        <title>Лабиринт</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="container">
        <h1>Hello</h1>
        <Maze />
      </div>
    </>
  )
}
